const opts = [
    { color: 'Không có gì', value: null, factor: null, error: null },
    { color: 'Đen', value: 0, factor: 1, error: 0 },
    { color: 'Nâu', value: 1, factor: 10, error: 1 },
    { color: 'Đỏ', value: 2, factor: 100, error: 2 },
    { color: 'Cam', value: 3, factor: 100, error: 0 },
    { color: 'Vàng', value: 4, factor: 1000, error: 0 },
    { color: 'Xanh lá - Lục', value: 5, factor: 10000, error: 0.5 },
    { color: 'Xanh dương - Lam', value: 6, factor: 100000, error: 0.25 },
    { color: 'Tím', value: 7, factor: 1000000, error: 0.1 },
    { color: 'Xám', value: 8, factor: 10000000, error: 0.05 },
    { color: 'Trắng', value: 9, factor: 100000000, error: 0 },
    { color: 'Vàng nhũ - Hoàng kim', value: 0, factor: 0, error: 5 },
    { color: 'Bạc', value: 0, factor: 0, error: 10 },
    { color: 'Không màu', value: 0, factor: 0, error: 20 },
];